### ISSUE TITLE
drop down list of airports in desktop version

### ISSUE THREAD

**Issue by stochmal** [fboes/aerofly-wettergeraet#1]
Is it possible to extend list of airports in the drop down via config file?

**Comment by fboes** [comment]
I am sorry, but currently the list of airports is…

* hardcoded (https://github.com/fboes/aerofly-wettergeraet/blob/master/src/WettergeraetDesktop/Frame.cpp#L245-L251),
* or read from `main.mcf` (https://github.com/fboes/aerofly-wettergeraet/blob/master/src/WettergeraetDesktop/Frame.cpp#L353-L364).

I have never come around to add an INI file or something similar, even though there are lots of configuration options begging for it.

Maybe there is some clever C++ programmer out there willing to add this feature? Maybe if you ask on the Aerofly forum there is some with enough time to add this feature?

**Comment by stochmal** [comment]
I am software developer but C# and Python. Probably could recompile your source code and add to static list for now.

Which version of Visual Studio did you used last time?

**Comment by stochmal** [comment]
I noticed you can read the flight plan which should be good enough for me. Thanks

**Comment by stochmal** [comment]
My own contribution to Aerofly FS2 at https://gitlab.com/stochmal/aerofly-fs2

**Comment by fboes** [comment]
If you are still interested in joing the development, there is a `CONTRIBUTING.md` attached to the project. For now I am closing this ticket.

**Comment by stochmal** [comment]
I did compile and debug your code so conclusion was that service returns blank response for some queries.
