### ISSUE TITLE
using flight plan airport location

### ISSUE THREAD

**Issue by stochmal** [fboes/aerofly-wettergeraet#2]
![image](https://user-images.githubusercontent.com/12511085/87436656-9bcc4d00-c5ed-11ea-8bdf-357c5bbceab8.png)

Query works from browser but not from desktop app. I noticed unsecure socket connection.

If I select KSFO then it works but not for LSPU

**Comment by stochmal** [comment]
I think when API can't find airport code then it just returns blank response.

**Comment by fboes** [comment]
@stochmal Fixed it:

* Better error output
* Changed API to use HTTPS (back in the days it was only available via HTTP)

**Comment by stochmal** [comment]
Thanks
